---
title: Half-Baked Ideas
author: Pranay Venkatesh
---

# What is this?

It has been a goal of mine for a long time to maintain a set of notebooks with half-baked ideas that I can keep referencing. These are not serious or even detailed discussion and they are not part of my official research work. But they are bits of academic or technical curiosity that are as advertised half-baked, and hence are not well-developed ideas. Often they are just bits of basic maths that I keep forgetting. They may relate to any one of my several interests in science, mathematics, engineering, technology, philosophy, history, economics or whatever else. I was alternatively thinking of calling this "notes with code" since they are visual or at least programmatic descriptions at times, but I felt it wasn't as apt as "half-baked ideas".



# Notebooks :
- [Direct Products, Direct Sums and Entanglement](https://chemicalfiend.github.io/half-baked-ideas/otimesplus.html)
- [Matrix Factorisations (SVD, QR)](https://chemicalfiend.github.io/half-baked-ideas/MatrixFactorisations.html)
- [The Julia Programming Language](https://chemicalfiend.github.io/half-baked-ideas/julia.html)
