#+OPTIONS: toc:nil
#+TITLE: Half-Baked Ideas
#+AUTHOR: Pranay Venkatesh

* What is this?
It has been a goal of mine for a long time to maintain a set of notebooks with half-baked ideas that I can keep referencing. I push it to the web so that the same resources are available to others. These are not serious opinion and they are not part of my official research work. But they are bits of academic or technical curiosity that are as advertised half-baked, and hence are not well-developed ideas. They may relate to any one of my several interests in science, mathematics, engineering, technology, anime, video games, travel and other things. I was alternatively thinking of calling this [[https://chemicalfiend.github.io/half-baked-ideas/orgmode.html][notes with code]] since they are visual or at least programmatic descriptions at times, but I felt it wasn't as apt as "half-baked ideas".



* Notebooks :
- [[https://chemicalfiend.github.io/half-baked-ideas/MatrixFactorisations.html][Matrix Factorisations (SVD, QR)]]
- [[https://chemicalfiend.github.io/half-baked-ideas/julia.html][The Julia Programming Language]]
- [[https://chemicalfiend.github.io/half-baked-ideas/uk.html][The United Kingdom]]
- [[https://chemicalfiend.github.io/half-baked-ideas/orgmode.html][orgmode and notes with code]]
