---
title: The United Kingdom
author: Pranay Venkatesh
---

# Things to do there

I spent 6 months in the UK for my masters thesis and I loved every bit of it. It's a great travel destination. A lot of people ask me where to go and what to see. This is what I did and recommend. I'm not a travel guide of course but these were fun things to do:

- Waterloo and Westminster: Waterloo Station, Southbank and BFI (biggest Imax theatre in Europe), Westminster Abbey, Trafalgar Square, Covent Garden, Buckingham Palace
- British Museum : you can spend a whole week there it's so vast!
- Baker Street, Sherlock Holmes Museum, Regents Park, go around UCL
- Soho : Catch a show at Piccadilly Circus (like Book of Mormon!), Walk around soho and Chinatown, Picadilly Circus, Leicester Square
- City of London Area: Tower of London (Koh-i-noor!!), Tower Bridge, Get a view from Skygarden (which is free unlike the overpriced view from the Shard)
- For sports fans: Go to Lords, Wimbledon, Wembley. I didn't do this and regret it almost every day.
- Catch a musical performance at the Barbican it's a fantastic venue.
- A Day in Greenwich: (Note : you should go here via ThamesLink trains or by taking the boat ride along the Thames; do NOT go by taking the bus from Peckham particularly if you want a tourist experience) Greenwich Market, Cutty Sark, Greenwich Park, Royal Observatory (another great view of the London skyline). Maritime Museum Queen's House Look around Canary Wharf, Docklands Museum. 
- Milton-Keynes: Red Bull Racing HQ, Bletchley Park, Museum for Computing,
- York: Jorvik Viking Centre, The York Dungeon, Castle Museum, Clifford's Tower.
- Oxford
- Windsor, Stonehenge and Bath

# UK as a Country

# London as a city


# To-Read

- London: The Biography, Peter Ackroyd
- London: A Social History, Roy Porter 
- Empire: How Britain Made the Modern World, Niall Ferguson
- A Short History of England, Simon Jenkins
- Nelson: Britannia's God of War, Andrew Lambert
