
# On Writing (academic)

My writing isn't great. I tend not to be able to structure arguments into a story well enough that the message I am trying to convey really lands. English-wise, I have decent conversational English, but my ability to write and speak well in terms of literary or academic or formal English is, while passable, well short of anything spectacular. This page hence serves as a placeholder for resources regarding primarily "academic writing", which in my head refers to the gamut of everything from putting words on metaphorical paper to making pretty plots and descriptive figures.

I usually prefer using LaTeX or Quarto markdown to make notes and write academic or adjacent things. For presentations, Beamer can be quite finnicky, particularly when there's figures involved. I like using LibreOffice with the LaTeX equations extensions to be able to toss in well-formatted equations when required and using CMU Serif gives everything a LaTeX touch.

Words

- Penguin Writer's Manual
- Economist Style Guide
- Steven Pinker Sense of Style

Plotting

- [Gnuplot tricks](https://gnuplot-tricks.blogspot.com/)
- [Beautiful Makie](https://beautiful.makie.org)
- [Coolor](https://coolor.co)

Figures

- [Inkscape for Lec Notes](https://castel.dev/post/lecture-notes-2/)





