---
title: Anime and Manga
author: Pranay Venkatesh
---

I spend a decent amount of time watching anime (and reading manga). These are some notes on my favourite anime and manga and there are some occassional reviews / external notes on creators or styles dropped in. 

# The Case for Anime

I think that in the 21st century, anime is probably the best medium of entertainment. Fantastic stories are told, sometimes leaving you thinking for days about abstract ideas and sometimes leaving you emotionally shattered. The medium also seems to get better (at least in some aspects) with every passing season, something I don't really think other media share.

# Anime / Manga Recommendations

This is not a comprehensive list of all the anime that I have watched or manga I have read. These are just the shows that I strongly recommend or I think about a lot or I go back and re-watch them or moments from them from time-to-time. Mostly I discuss shows that are completed or at least have matured to the point that they have solidified their place as an absolute great in my mind.

I categorise anime based on some of my favourite genres: 

# Shounen

- [One Piece](https://chemicalfiend.github.io/anime/one-piece.html)
- Gintama
- Hunter x Hunter

# Seinen

- Vinland Saga
- Vagabond 

# Science Fiction

- Neon Genesis Evangelion
- Ginga Eiyuu Densetsu
- Psycho-Pass

# Isekai / Fantasy

# Romance / Slice of Life

- Hyouka
- Blue Box
- NHK 


